title: Tommy Ip
author: Tommy Ip
email: hkmp7tommy@gmail.com
description: Tommy Ip's personal website. About me | projects | blog
baseurl: ""
url: "http://tommyip.me"
github_username: tommyip

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:title/
