title: Tommy Ip
author: Tommy Ip
email: hkmp7tommy@gmail.com
description: |
    Tommy Ip is a open source advocate and high school student,
    found more about him and his blog here.
baseurl: ""
url: "http://tommyip.me"
github_username: tommyip

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:title/
